config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'tweets#index'

get 'tweets', to: 'tweets#index'
get 'tweets/new', to: 'tweets#new'
post 'tweets',  to: 'tweets#create'
get 'tweets/:id', to: 'tweets#show', as: :tweet
get 'tweets/:id/edit', to: 'tweets#edit', as: :edit_tweet
put 'tweets', to: 'tweets#update'
patch 'tweets', to: 'tweets#update'
delete 'tweets/:id', to: 'tweets#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all
  end

  def new
    @tweets = Tweet.new
  end

  def create
    @tweets = Tweet.new(tweet_params)

    if @tweet.save
      redirect_to_tweets_path
    else
      render :new
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def delete
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to_tweets_path
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])

    if @tweet.update_attributes(tweet_params)
      redirect_to_tweets_path
    else
      render :edit
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:handle, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Today's Tweets</h1>

<ul>
    <% @tweets.each do |tweet| %>
        <li>
            <strong><%= link_to tweet.handle, tweet_path(tweet) %></strong> - <%= tweet.content %>
        </li>
    <% end %>
</ul>

app/views/tweets/show.html.erb
<h1><%= @tweet.handle %></h1>

<p>This account is for <%= @tweet.handle %> and this is what they have to say <%= @tweet.content %>.</p>

<%= link_to "Back to the tweets!", tweets_path %>